version: "2"
linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errchkjson
    - gochecknoinits
    - goconst
    - gocyclo
    - godox
    - goprintffuncname
    - govet
    - grouper
    - ineffassign
    - intrange
    - ireturn
    - maintidx
    - misspell
    - nakedret
    - nilnil
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
