version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

defaults: &defaults
  working_directory: /src
  docker:
    - image: golang:1.14

jobs:
  lint_markdown:
    <<: *defaults
    docker:
      - image: node:12-slim
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .

  build_source:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Source
          command: go build -mod=readonly ./...

  lint_source:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.7
      - run:
          name: Check for Lint
          command: golangci-lint run

  unit_test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test -coverprofile cover.out -race ./...
      - codecov/upload:
          file: cover.out

workflows:
  version: 2

  build_and_test:
    jobs:
      - lint_markdown
      - build_source
      - lint_source
      - unit_test
