version: 2.1

orbs:
  codecov: codecov/codecov@1.1

executors:
  node:
    docker:
      - image: node:14-slim
  golang:
    docker:
      - image: golang:1.14
  golangci-lint:
    docker:
      - image: golangci/golangci-lint:v1.30-alpine

jobs:
  lint_markdown:
    executor: node
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .

  check_mod_tidy:
    executor: golang
    steps:
      - checkout
      - run:
          name: Go Mod Tidy
          command: go mod tidy
      - run:
          name: Check Module Tidiness
          command: git diff --exit-code -- go.mod go.sum

  build_source:
    executor: golang
    steps:
      - checkout
      - run:
          name: Build Source
          command: go build ./...

  lint_source:
    executor: golangci-lint
    steps:
      - checkout
      - run:
          name: Check for Lint
          command: golangci-lint run

  unit_test:
    executor: golang
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test -coverprofile cover.out -race ./...
      - codecov/upload:
          file: cover.out

workflows:
  version: 2

  build_and_test:
    jobs:
      - lint_markdown
      - check_mod_tidy
      - build_source
      - lint_source
      - unit_test
